USE TERMINARZ;

CREATE TABLE USERS_TBL(
USERNAME VARCHAR(20) CHARACTER SET UTF8MB4	NOT NULL,
PASS VARCHAR(30) CHARACTER SET UTF8MB4	NOT NULL,
PRIMARY KEY (USERNAME)
);

CREATE TABLE EVENTS_TBL(
ID INT NOT NULL AUTO_INCREMENT,
DEADLINE DATETIME NOT NULL,
NAME_OF_EVENT VARCHAR(20) CHARACTER SET UTF8MB4	NOT NULL,
USERNAME VARCHAR(20) CHARACTER SET UTF8MB4	NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (USERNAME) REFERENCES USERS_TBL (USERNAME)
);
